version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    rebase-strategy: auto
    versioning-strategy: increase
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Asia/Jakarta'
    target-branch: 'master'
  - package-ecosystem: 'github-actions'
    directory: '/'
    rebase-strategy: auto
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Asia/Jakarta'
    target-branch: 'master'
